/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_classes.py", line 237, in fit
    self.loss, sample_weight=sample_weight)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_base.py", line 969, in _fit_liblinear
    epsilon, sample_weight)
  File "sklearn/svm/_liblinear.pyx", line 39, in sklearn.svm._liblinear.train_wrap
OverflowError: value too large to convert to npy_int32

  FitFailedWarning)
/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_classes.py", line 237, in fit
    self.loss, sample_weight=sample_weight)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_base.py", line 969, in _fit_liblinear
    epsilon, sample_weight)
  File "sklearn/svm/_liblinear.pyx", line 39, in sklearn.svm._liblinear.train_wrap
OverflowError: value too large to convert to npy_int32

  FitFailedWarning)
/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_classes.py", line 237, in fit
    self.loss, sample_weight=sample_weight)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_base.py", line 969, in _fit_liblinear
    epsilon, sample_weight)
  File "sklearn/svm/_liblinear.pyx", line 39, in sklearn.svm._liblinear.train_wrap
OverflowError: value too large to convert to npy_int32

  FitFailedWarning)
/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_classes.py", line 237, in fit
    self.loss, sample_weight=sample_weight)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_base.py", line 969, in _fit_liblinear
    epsilon, sample_weight)
  File "sklearn/svm/_liblinear.pyx", line 39, in sklearn.svm._liblinear.train_wrap
OverflowError: value too large to convert to npy_int32

  FitFailedWarning)
/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_classes.py", line 237, in fit
    self.loss, sample_weight=sample_weight)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_base.py", line 969, in _fit_liblinear
    epsilon, sample_weight)
  File "sklearn/svm/_liblinear.pyx", line 39, in sklearn.svm._liblinear.train_wrap
OverflowError: value too large to convert to npy_int32

  FitFailedWarning)
Traceback (most recent call last):
  File "modelling-rawvoxels-sep9.py", line 149, in <module>
    model.fit(X,y)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_classes.py", line 237, in fit
    self.loss, sample_weight=sample_weight)
  File "/nethome/kcni/posborne/.local/lib/python3.6/site-packages/sklearn/svm/_base.py", line 969, in _fit_liblinear
    epsilon, sample_weight)
  File "sklearn/svm/_liblinear.pyx", line 39, in sklearn.svm._liblinear.train_wrap
OverflowError: value too large to convert to npy_int32
